name: splunk

services:
  splunk:
    image: splunk/splunk:10.0
    container_name: splunk
    platform: linux/amd64
    ports:
      - "8001:8000"
      - "8089:8089"
    environment:
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: password

